# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm install --ignore-scripts && npm run build

FROM node:lts-alpine
WORKDIR /app
COPY --from=builder /app/build ./build
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts

# Ensure the entrypoint script is executable
RUN chmod +x build/index.js

ENTRYPOINT ["node", "build/index.js"]
